name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up MySQL
      run: sudo apt-get install mysql-client

    - name: Deploy Initial Schema
      run: mysql -h ${{ secrets.DB_HOST }} -u ${{ secrets.DB_USER }} -p${{ secrets.DB_PASSWORD }} < ./sql/create_table.sql

    - name: Add Humidity Column
      run: mysql -h ${{ secrets.DB_HOST }} -u ${{ secrets.DB_USER }} -p${{ secrets.DB_PASSWORD }} < ./sql/add_column.sql

    - name: Seed Data
      run: mysql -h ${{ secrets.DB_HOST }} -u ${{ secrets.DB_USER }} -p${{ secrets.DB_PASSWORD }} < ./sql/seed_data.sql

    - name: Run Concurrent Queries
      run: python3 ./scripts/multi_thread_queries.py
